import { Asset, AssetHistoryEvent } from "../types";

export const mockAssets: Asset[] = [
  {
    id: "ast-001",
    code: "ASC-001",
    name: "Ascensor Principal Torre A",
    category: "Ascensores",
    location: "Torre A – Todos los pisos",
    status: "Operativo",
    installationDate: "2018-03-15",
    lastMaintenance: "2025-02-10",
    nextMaintenance: "2025-05-10",
    description: "Ascensor hidráulico de 8 personas. Capacidad 630 kg. Marca OTIS.",
    observations: "Revisión semestral de cables y sistema hidráulico completada sin novedades.",
    providerId: "prov-001",
    serialNumber: "OT-2018-A4421",
    brand: "OTIS",
    model: "Gen2 Comfort",
  },
  {
    id: "ast-002",
    code: "ASC-002",
    name: "Ascensor Servicio Torre B",
    category: "Ascensores",
    location: "Torre B – Sótano a Piso 12",
    status: "En Mantenimiento",
    installationDate: "2019-07-22",
    lastMaintenance: "2025-03-01",
    nextMaintenance: "2025-04-01",
    description: "Ascensor de servicio para carga. Capacidad 1000 kg.",
    observations: "En mantenimiento correctivo por ruido en puerta del piso 4. Estimado 5 días hábiles.",
    providerId: "prov-001",
    serialNumber: "SCH-2019-B2231",
    brand: "Schindler",
    model: "3300 AP",
  },
  {
    id: "ast-003",
    code: "EXT-001",
    name: "Extintores Lobby Principal",
    category: "Extintores",
    location: "Lobby – Planta Baja",
    status: "Operativo",
    installationDate: "2020-01-10",
    lastMaintenance: "2025-01-15",
    nextMaintenance: "2026-01-15",
    description: "Set de 3 extintores ABC de 10kg. Última carga y verificación en enero 2025.",
    observations: "Todos en estado óptimo. Próxima recarga programada para enero 2026.",
    providerId: "prov-002",
    brand: "Kidde",
    model: "Pro 10",
  },
  {
    id: "ast-004",
    code: "EXT-002",
    name: "Extintores Sótano",
    category: "Extintores",
    location: "Sótano – Nivel -1",
    status: "Vencido",
    installationDate: "2020-01-10",
    lastMaintenance: "2024-01-20",
    nextMaintenance: "2025-01-20",
    description: "Set de 2 extintores CO2 de 5kg para cuarto de máquinas.",
    observations: "ALERTA: Vencidos desde enero 2025. Requiere recarga urgente.",
    providerId: "prov-002",
    brand: "Amerex",
    model: "B5T",
  },
  {
    id: "ast-005",
    code: "CCTV-001",
    name: "Cámara CCTV Entrada Principal",
    category: "CCTV",
    location: "Entrada Principal – Exterior",
    status: "Operativo",
    installationDate: "2021-05-20",
    lastMaintenance: "2025-02-01",
    nextMaintenance: "2025-05-01",
    description: "Cámara IP 4K con visión nocturna y detección de movimiento. Marca Hikvision.",
    observations: "Funcionamiento óptimo. Almacenamiento en NVR local con retención de 30 días.",
    providerId: "prov-003",
    serialNumber: "HK-DS2CD2T47G2-L",
    brand: "Hikvision",
    model: "DS-2CD2T47G2",
  },
  {
    id: "ast-006",
    code: "CCTV-002",
    name: "Sistema CCTV Parking",
    category: "CCTV",
    location: "Parking – Nivel -1 y -2",
    status: "Falla",
    installationDate: "2021-05-20",
    lastMaintenance: "2024-11-15",
    nextMaintenance: "2025-02-15",
    description: "Sistema de 6 cámaras para cobertura total del parking.",
    observations: "FALLA: 2 cámaras sin señal desde 05/03. Técnico asignado. Estimado reparación: 48 h.",
    providerId: "prov-003",
    serialNumber: "HK-NVR-4CH-2025",
    brand: "Hikvision",
    model: "NVR DS-7616NI",
  },
  {
    id: "ast-007",
    code: "ELEC-001",
    name: "Tablero Eléctrico Principal",
    category: "Sistema Eléctrico",
    location: "Cuarto Eléctrico – Planta Baja",
    status: "Operativo",
    installationDate: "2017-08-01",
    lastMaintenance: "2025-01-05",
    nextMaintenance: "2025-07-05",
    description: "Tablero de distribución trifásico 400A. Incluye protecciones diferenciales y termomagnéticas.",
    observations: "Revisión semestral sin anomalías. Documentación actualizada.",
    providerId: "prov-004",
    brand: "Schneider Electric",
    model: "Prisma Plus",
  },
  {
    id: "ast-008",
    code: "ELEC-002",
    name: "Generador Emergencia",
    category: "Sistema Eléctrico",
    location: "Cuarto Técnico – Sótano",
    status: "Operativo",
    installationDate: "2019-03-10",
    lastMaintenance: "2025-02-20",
    nextMaintenance: "2025-08-20",
    description: "Generador diesel 60kVA para suministro de emergencia. Autonomía estimada 8 horas.",
    observations: "Test de arranque mensual satisfactorio. Nivel de combustible al 80%.",
    providerId: "prov-004",
    brand: "Cummins",
    model: "C60D5e",
  },
  {
    id: "ast-009",
    code: "BOMB-001",
    name: "Bomba de Agua Principal",
    category: "Bombas de Agua",
    location: "Cuarto de Máquinas – Sótano",
    status: "Operativo",
    installationDate: "2018-06-15",
    lastMaintenance: "2025-02-10",
    nextMaintenance: "2025-04-10",
    description: "Bomba centrífuga trifásica 5.5HP. Sistema de presurización para toda la torre.",
    observations: "Presión dentro de parámetros normales. Sin fugas detectadas.",
    providerId: "prov-005",
    brand: "Grundfos",
    model: "CM5-7 A-R-I-E-AQQE",
  },
  {
    id: "ast-010",
    code: "BOMB-002",
    name: "Bomba de Agua Secundaria",
    category: "Bombas de Agua",
    location: "Cuarto de Máquinas – Sótano",
    status: "En Mantenimiento",
    installationDate: "2018-06-15",
    lastMaintenance: "2025-03-05",
    nextMaintenance: "2025-05-05",
    description: "Bomba de respaldo para contingencias. Mismo modelo que principal.",
    observations: "En mantenimiento preventivo programado. Reemplazo de sellos mecánicos.",
    providerId: "prov-005",
    brand: "Grundfos",
    model: "CM5-7 A-R-I-E-AQQE",
  },
  {
    id: "ast-011",
    code: "ACI-001",
    name: "Central de Alarma Contra Incendio",
    category: "Alarmas CI",
    location: "Recepción – Planta Baja",
    status: "Operativo",
    installationDate: "2020-09-01",
    lastMaintenance: "2025-01-20",
    nextMaintenance: "2025-07-20",
    description: "Central analógica direccionable con 128 puntos. Cubre todos los pisos.",
    observations: "Prueba semestral completada. Todos los detectores respondiendo correctamente.",
    providerId: "prov-002",
    brand: "Notifier",
    model: "NFS-3030",
  },
  {
    id: "ast-012",
    code: "NET-001",
    name: "Router Principal Edificio",
    category: "Internet",
    location: "Cuarto de Telecomunicaciones – PB",
    status: "Operativo",
    installationDate: "2022-02-14",
    lastMaintenance: "2025-02-20",
    nextMaintenance: "2025-05-20",
    description: "Router empresarial con conectividad fibra óptica 500Mbps. Red principal del edificio.",
    observations: "Uptime 99.8% en últimos 30 días. Firmware actualizado.",
    providerId: "prov-006",
    brand: "Cisco",
    model: "RV345 Dual WAN",
  },
  {
    id: "ast-013",
    code: "AC-001",
    name: "Área Común – Lobby Principal",
    category: "Áreas Comunes",
    location: "Planta Baja",
    status: "Operativo",
    installationDate: "2017-01-01",
    lastMaintenance: "2025-03-01",
    nextMaintenance: "2025-04-01",
    description: "Lobby de acceso con iluminación LED, sistema de control de acceso y recepción.",
    observations: "Limpieza y mantenimiento mensual al día. Sin observaciones.",
    providerId: "prov-007",
  },
  {
    id: "ast-014",
    code: "AC-002",
    name: "Área Común – Salón de Usos Múltiples",
    category: "Áreas Comunes",
    location: "Piso 1",
    status: "Operativo",
    installationDate: "2017-01-01",
    lastMaintenance: "2025-02-28",
    nextMaintenance: "2025-03-31",
    description: "SUM con capacidad para 80 personas. Incluye proyector, sonido y aire acondicionado.",
    observations: "Equipamiento audiovisual en buen estado. Próxima limpieza de AC programada.",
    providerId: "prov-007",
  },
];

export const mockAssetHistory: AssetHistoryEvent[] = [
  {
    id: "evt-001",
    assetId: "ast-001",
    date: "2025-02-10",
    type: "Mantenimiento",
    title: "Mantenimiento preventivo semestral",
    description: "Revisión completa del sistema hidráulico, cables, puertas y sistema de control.",
    technician: "Ing. Roberto Vargas",
  },
  {
    id: "evt-002",
    assetId: "ast-001",
    date: "2024-08-15",
    type: "Mantenimiento",
    title: "Mantenimiento preventivo semestral",
    description: "Lubricación de guías, ajuste de frenos y verificación de sistema eléctrico.",
    technician: "Ing. Roberto Vargas",
  },
  {
    id: "evt-003",
    assetId: "ast-001",
    date: "2024-03-10",
    type: "Incidencia",
    title: "Falla en sensor de puerta – Piso 7",
    description: "Sensor de apertura de puerta descalibrado. Reemplazo de sensor realizado.",
    technician: "Tec. Mario Suárez",
  },
  {
    id: "evt-004",
    assetId: "ast-001",
    date: "2023-09-20",
    type: "Inspección",
    title: "Inspección reglamentaria anual",
    description: "Inspección oficial por ente regulador. Certificado de habilitación renovado.",
    technician: "Inspector Municipal",
  },
  {
    id: "evt-005",
    assetId: "ast-001",
    date: "2018-03-15",
    type: "Instalación",
    title: "Instalación inicial",
    description: "Instalación y puesta en marcha del equipo. Pruebas de carga y nivelación.",
    technician: "Equipo TecnoAscensores",
  },
  {
    id: "evt-006",
    assetId: "ast-006",
    date: "2025-03-05",
    type: "Incidencia",
    title: "Falla en cámaras C3 y C5 del parking",
    description: "Pérdida de señal en cámaras 3 y 5. Posible daño en cableado por humedad.",
    technician: "Tec. Pablo Moreno",
  },
  {
    id: "evt-007",
    assetId: "ast-006",
    date: "2024-11-15",
    type: "Mantenimiento",
    title: "Mantenimiento preventivo trimestral",
    description: "Limpieza de lentes, ajuste de ángulos y verificación de grabación.",
    technician: "Tec. Pablo Moreno",
  },
];
