import { Document } from "../types";

export const mockDocuments: Document[] = [
  {
    id: "doc-001",
    name: "Manual de Usuario – Ascensor OTIS Gen2",
    type: "Manual",
    assetId: "ast-001",
    providerId: "prov-001",
    uploadedBy: "Admin. Edificio",
    uploadedAt: "2018-04-01",
    fileSize: "4.2 MB",
    fileType: "PDF",
    description: "Manual técnico y de usuario del ascensor principal Torre A.",
    tags: ["ascensor", "OTIS", "manual técnico"],
  },
  {
    id: "doc-002",
    name: "Certificado Habilitación Ascensor ASC-001",
    type: "Certificado",
    assetId: "ast-001",
    uploadedBy: "Admin. Edificio",
    uploadedAt: "2024-03-20",
    expiresAt: "2025-03-20",
    fileSize: "1.1 MB",
    fileType: "PDF",
    description: "Certificado de habilitación municipal vigente. Inspección anual aprobada.",
    tags: ["certificado", "habilitación", "ascensor"],
  },
  {
    id: "doc-003",
    name: "Contrato Mantenimiento – TecnoAscensores",
    type: "Contrato",
    providerId: "prov-001",
    uploadedBy: "Admin. Edificio",
    uploadedAt: "2024-01-15",
    expiresAt: "2026-01-15",
    fileSize: "2.8 MB",
    fileType: "PDF",
    description: "Contrato de mantenimiento anual para ambos ascensores. Incluye SLA y coberturas.",
    tags: ["contrato", "ascensores", "mantenimiento"],
  },
  {
    id: "doc-004",
    name: "Informe Técnico – Mantenimiento Eléctrico Q1 2025",
    type: "Informe Técnico",
    assetId: "ast-007",
    providerId: "prov-004",
    uploadedBy: "ElectroPlan S.R.L.",
    uploadedAt: "2025-01-10",
    fileSize: "3.5 MB",
    fileType: "PDF",
    description: "Informe detallado de la revisión semestral del tablero eléctrico principal.",
    tags: ["eléctrico", "informe", "tablero", "Q1-2025"],
  },
  {
    id: "doc-005",
    name: "Plano Eléctrico – Planta Baja y Sótano",
    type: "Plano",
    assetId: "ast-007",
    uploadedBy: "Admin. Edificio",
    uploadedAt: "2021-06-01",
    fileSize: "8.7 MB",
    fileType: "PDF",
    description: "Planos eléctricos actualizados de planta baja y sótano del edificio.",
    tags: ["plano", "eléctrico", "arquitectura"],
  },
  {
    id: "doc-006",
    name: "Certificado Recarga Extintores – 2025",
    type: "Certificado",
    assetId: "ast-003",
    providerId: "prov-002",
    uploadedBy: "FireSafe Argentina",
    uploadedAt: "2025-01-20",
    expiresAt: "2026-01-20",
    fileSize: "0.9 MB",
    fileType: "PDF",
    description: "Certificado de recarga y verificación de extintores del lobby principal.",
    tags: ["extintores", "certificado", "recarga"],
  },
  {
    id: "doc-007",
    name: "Contrato Vigilancia – VigilTech Seguridad",
    type: "Contrato",
    providerId: "prov-003",
    uploadedBy: "Admin. Edificio",
    uploadedAt: "2024-06-01",
    expiresAt: "2025-06-01",
    fileSize: "1.6 MB",
    fileType: "PDF",
    description: "Contrato de mantenimiento trimestral del sistema CCTV.",
    tags: ["CCTV", "contrato", "seguridad"],
  },
  {
    id: "doc-008",
    name: "Informe Técnico – Sistema Hidráulico 2024",
    type: "Informe Técnico",
    assetId: "ast-009",
    providerId: "prov-005",
    uploadedBy: "HidroServ Ltda.",
    uploadedAt: "2024-12-10",
    fileSize: "2.2 MB",
    fileType: "PDF",
    description: "Informe de revisión anual de bombas y sistema hidráulico.",
    tags: ["bombas", "hidráulico", "informe"],
  },
  {
    id: "doc-009",
    name: "Manual Sistema Alarma – Notifier NFS-3030",
    type: "Manual",
    assetId: "ast-011",
    providerId: "prov-002",
    uploadedBy: "FireSafe Argentina",
    uploadedAt: "2020-09-15",
    fileSize: "6.1 MB",
    fileType: "PDF",
    description: "Manual técnico completo de la central de alarma contra incendio.",
    tags: ["alarma", "incendio", "manual", "Notifier"],
  },
  {
    id: "doc-010",
    name: "Plano General del Edificio – Planta Arquitectónica",
    type: "Plano",
    uploadedBy: "Admin. Edificio",
    uploadedAt: "2017-03-01",
    fileSize: "12.4 MB",
    fileType: "PDF",
    description: "Planos arquitectónicos completos del edificio. Todos los pisos.",
    tags: ["plano", "arquitectura", "general"],
  },
  {
    id: "doc-011",
    name: "Contrato Internet Corporativo – NetConnect",
    type: "Contrato",
    assetId: "ast-012",
    providerId: "prov-006",
    uploadedBy: "Admin. Edificio",
    uploadedAt: "2024-02-14",
    expiresAt: "2025-02-14",
    fileSize: "1.3 MB",
    fileType: "PDF",
    description: "Contrato de servicio de internet fibra óptica 500Mbps para el edificio.",
    tags: ["internet", "contrato", "NetConnect"],
  },
  {
    id: "doc-012",
    name: "Informe Inspección CCTV – Febrero 2025",
    type: "Informe Técnico",
    assetId: "ast-005",
    providerId: "prov-003",
    uploadedBy: "VigilTech Seguridad",
    uploadedAt: "2025-02-05",
    fileSize: "1.8 MB",
    fileType: "PDF",
    description: "Informe de mantenimiento preventivo del sistema CCTV entrada principal.",
    tags: ["CCTV", "informe", "mantenimiento"],
  },
];
