import { Incident, IncidentEvent } from "../types";

export const mockIncidents: Incident[] = [
  {
    id: "inc-001",
    code: "INC-2025-001",
    title: "Extintores del sótano vencidos",
    description:
      "Los 2 extintores CO2 del cuarto de máquinas en el sótano nivel -1 están vencidos desde enero 2025. Se requiere recarga urgente para cumplir normativa de seguridad.",
    assetId: "ast-004",
    priority: "Crítica",
    status: "Abierta",
    reportedBy: "Admin. Edificio",
    assignedTo: "FireSafe Argentina",
    createdAt: "2025-02-05T09:00:00Z",
    updatedAt: "2025-03-05T10:30:00Z",
    observations: "Proveedor contactado. Pendiente confirmación de fecha de visita.",
    hasEvidence: true,
  },
  {
    id: "inc-002",
    code: "INC-2025-002",
    title: "Falla en cámaras CCTV del parking",
    description:
      "Las cámaras C3 y C5 del parking nivel -1 y -2 perdieron señal el 05/03/2025. Posible daño en cableado por filtraciones de humedad en el sector sur.",
    assetId: "ast-006",
    priority: "Alta",
    status: "En Proceso",
    reportedBy: "Personal de Seguridad",
    assignedTo: "VigilTech Seguridad",
    createdAt: "2025-03-05T14:20:00Z",
    updatedAt: "2025-03-08T09:00:00Z",
    observations: "Técnico en sitio desde el 07/03. Diagnóstico: corte de cable en tramo D.",
    hasEvidence: true,
  },
  {
    id: "inc-003",
    code: "INC-2025-003",
    title: "Ruido anormal en ascensor servicio piso 4",
    description:
      "Vecinos reportan ruido metálico al pasar el ascensor de servicio por el piso 4. Se activó protocolo de mantenimiento correctivo.",
    assetId: "ast-002",
    priority: "Alta",
    status: "En Proceso",
    reportedBy: "Residente Piso 4B",
    assignedTo: "TecnoAscensores S.A.",
    createdAt: "2025-03-01T11:00:00Z",
    updatedAt: "2025-03-06T16:00:00Z",
    observations: "Ascensor fuera de servicio. Reparación en curso. ETA: 05 días hábiles.",
    hasEvidence: false,
  },
  {
    id: "inc-004",
    code: "INC-2025-004",
    title: "Iluminación del parking nivel -2 intermitente",
    description:
      "Varias luminarias del sector de estacionamiento nivel -2 presentan parpadeo y apagado intermitente. Posible falla en circuito secundario.",
    assetId: "ast-007",
    priority: "Media",
    status: "Abierta",
    reportedBy: "Propietario Cochera 45",
    createdAt: "2025-03-07T18:30:00Z",
    updatedAt: "2025-03-07T18:30:00Z",
    hasEvidence: false,
  },
  {
    id: "inc-005",
    code: "INC-2025-005",
    title: "Filtración de agua en cuarto de máquinas",
    description:
      "Se detectó humedad en las paredes del cuarto de máquinas adyacente a la bomba secundaria. Posible origen: cañería de agua fría.",
    assetId: "ast-010",
    priority: "Alta",
    status: "En Proceso",
    reportedBy: "Encargado del Edificio",
    assignedTo: "HidroServ Ltda.",
    createdAt: "2025-03-04T08:00:00Z",
    updatedAt: "2025-03-05T14:00:00Z",
    resolvedAt: undefined,
    observations: "HidroServ inspeccionó el 05/03. Trabajo de sellado programado para el 10/03.",
    hasEvidence: true,
  },
  {
    id: "inc-006",
    code: "INC-2025-006",
    title: "Falla sensor detector humo piso 8",
    description:
      "Detector de humo del pasillo piso 8 activó alarma sin causa aparente. Posible falla técnica del sensor.",
    assetId: "ast-011",
    priority: "Media",
    status: "Resuelta",
    reportedBy: "Central de Alarmas",
    assignedTo: "FireSafe Argentina",
    createdAt: "2025-02-20T22:10:00Z",
    updatedAt: "2025-02-21T15:00:00Z",
    resolvedAt: "2025-02-21T15:00:00Z",
    observations: "Sensor reemplazado. Sistema verificado y funcionando correctamente.",
    hasEvidence: false,
  },
  {
    id: "inc-007",
    code: "INC-2025-007",
    title: "Interrupción servicio internet áreas comunes",
    description:
      "El wifi de las áreas comunes (lobby y SUM) no estuvo disponible por 4 horas el día 15/02.",
    assetId: "ast-012",
    priority: "Baja",
    status: "Cerrada",
    reportedBy: "Recepción",
    assignedTo: "NetConnect Pro",
    createdAt: "2025-02-15T10:00:00Z",
    updatedAt: "2025-02-15T14:30:00Z",
    resolvedAt: "2025-02-15T14:30:00Z",
    observations: "Reinicio de router resolvió el problema. Se detectó actualización automática de firmware como causa.",
    hasEvidence: false,
  },
  {
    id: "inc-008",
    code: "INC-2025-008",
    title: "Daño en puerta automática lobby",
    description:
      "La puerta automática del lobby principal no cierra correctamente. Sensor de presencia con falla.",
    assetId: "ast-013",
    priority: "Media",
    status: "Abierta",
    reportedBy: "Recepcionista",
    createdAt: "2025-03-09T07:45:00Z",
    updatedAt: "2025-03-09T07:45:00Z",
    hasEvidence: true,
  },
];

export const mockIncidentEvents: IncidentEvent[] = [
  {
    id: "iev-001",
    incidentId: "inc-001",
    date: "2025-02-05T09:00:00Z",
    type: "Creación",
    description: "Incidencia registrada por Admin. Edificio tras inspección visual.",
    author: "Admin. Edificio",
  },
  {
    id: "iev-002",
    incidentId: "inc-001",
    date: "2025-02-06T11:00:00Z",
    type: "Asignación",
    description: "Incidencia asignada a FireSafe Argentina para recarga urgente.",
    author: "Administrador",
  },
  {
    id: "iev-003",
    incidentId: "inc-001",
    date: "2025-03-05T10:30:00Z",
    type: "Actualización",
    description: "Proveedor contactado. Pendiente confirmación de fecha. Situación sigue sin resolver.",
    author: "Administrador",
  },
  {
    id: "iev-004",
    incidentId: "inc-002",
    date: "2025-03-05T14:20:00Z",
    type: "Creación",
    description: "Falla detectada por personal de seguridad durante ronda nocturna.",
    author: "Personal de Seguridad",
  },
  {
    id: "iev-005",
    incidentId: "inc-002",
    date: "2025-03-06T09:00:00Z",
    type: "Asignación",
    description: "Caso asignado a VigilTech. Se solicitó visita técnica urgente.",
    author: "Administrador",
  },
  {
    id: "iev-006",
    incidentId: "inc-002",
    date: "2025-03-07T10:00:00Z",
    type: "Actualización",
    description: "Técnico en sitio. Diagnóstico inicial: corte de cable en tramo D por humedad.",
    author: "Tec. Pablo Moreno",
  },
  {
    id: "iev-007",
    incidentId: "inc-002",
    date: "2025-03-08T09:00:00Z",
    type: "Actualización",
    description: "Material de reposición solicitado. Reparación estimada en 48hs.",
    author: "Tec. Pablo Moreno",
  },
  {
    id: "iev-008",
    incidentId: "inc-006",
    date: "2025-02-20T22:10:00Z",
    type: "Creación",
    description: "Alarma activada automáticamente. Sin humo visible. Personal verificó el área.",
    author: "Central de Alarmas",
  },
  {
    id: "iev-009",
    incidentId: "inc-006",
    date: "2025-02-21T10:00:00Z",
    type: "Asignación",
    description: "Técnico de FireSafe asignado para revisión del sensor.",
    author: "Administrador",
  },
  {
    id: "iev-010",
    incidentId: "inc-006",
    date: "2025-02-21T15:00:00Z",
    type: "Resolución",
    description: "Sensor defectuoso reemplazado. Sistema de alarma verificado y operativo.",
    author: "Tec. Marcela Díaz",
  },
];
