import { Provider } from "../types";

export const mockProviders: Provider[] = [
  {
    id: "prov-001",
    name: "TecnoAscensores S.A.",
    rubro: "Mantenimiento de Ascensores",
    contactName: "Ing. Roberto Vargas",
    contactEmail: "r.vargas@tecnoascensores.com",
    contactPhone: "+54 11 4322-7890",
    status: "Activo",
    lastService: "2025-02-15",
    rating: 4.8,
    contractType: "Mantenimiento Anual",
    categories: ["Ascensores"],
  },
  {
    id: "prov-002",
    name: "FireSafe Argentina",
    rubro: "Protección Contra Incendios",
    contactName: "Sra. Marcela Díaz",
    contactEmail: "m.diaz@firesafe.com.ar",
    contactPhone: "+54 11 5522-1100",
    status: "Activo",
    lastService: "2025-01-20",
    rating: 4.5,
    contractType: "Servicio Anual",
    categories: ["Extintores", "Alarmas CI"],
  },
  {
    id: "prov-003",
    name: "VigilTech Seguridad",
    rubro: "Sistemas de Vigilancia",
    contactName: "Sr. Pablo Moreno",
    contactEmail: "p.moreno@vigiltech.com",
    contactPhone: "+54 11 4411-9988",
    status: "Activo",
    lastService: "2025-02-01",
    rating: 4.2,
    contractType: "Mantenimiento Trimestral",
    categories: ["CCTV"],
  },
  {
    id: "prov-004",
    name: "ElectroPlan S.R.L.",
    rubro: "Instalaciones Eléctricas",
    contactName: "Ing. Carlos Soto",
    contactEmail: "c.soto@electroplan.com.ar",
    contactPhone: "+54 11 4800-3344",
    status: "Activo",
    lastService: "2025-01-10",
    rating: 4.6,
    contractType: "Por Demanda",
    categories: ["Sistema Eléctrico"],
  },
  {
    id: "prov-005",
    name: "HidroServ Ltda.",
    rubro: "Sistemas Hidráulicos",
    contactName: "Sr. Facundo Ríos",
    contactEmail: "f.rios@hidroserv.com",
    contactPhone: "+54 11 5677-2233",
    status: "Activo",
    lastService: "2025-02-10",
    rating: 4.4,
    contractType: "Mantenimiento Bimestral",
    categories: ["Bombas de Agua"],
  },
  {
    id: "prov-006",
    name: "NetConnect Pro",
    rubro: "Telecomunicaciones e Internet",
    contactName: "Lic. Valentina Torres",
    contactEmail: "v.torres@netconnect.com.ar",
    contactPhone: "+54 11 4933-5566",
    status: "Activo",
    lastService: "2025-02-20",
    rating: 4.0,
    contractType: "Servicio Mensual",
    categories: ["Internet"],
  },
  {
    id: "prov-007",
    name: "CleanBuild Servicios",
    rubro: "Mantenimiento General y Limpieza",
    contactName: "Sr. Gustavo Pérez",
    contactEmail: "g.perez@cleanbuild.com",
    contactPhone: "+54 11 4255-7744",
    status: "Pendiente Evaluación",
    lastService: "2025-01-05",
    rating: 3.8,
    contractType: "Mantenimiento Mensual",
    categories: ["Áreas Comunes"],
  },
];
